resources:
    App\Entity\EmailMessage:
        attributes:
            pagination_enabled: false
            normalization_context:
                groups: ['emailMessage-read']
            denormalization_context:
                groups: ['emailMessage-write']
            enable_max_depth: true
        collectionOperations:

            get:
                method: 'GET'
                access_control: is_granted('ROLE_USER')

            post:
                method: 'POST'
                access_control: is_granted('ROLE_USER')
        itemOperations:

            get:
                method: 'GET'
                access_control: is_granted('ROLE_USER')
                swagger_context:
                    summary: 'Return EmailMessage'