#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# FOSUserBundle
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# FOSAuthServer
fos_oauth_server_token:
    path: /api/login
    controller: fos_oauth_server.controller.token:tokenAction

fos_oauth_server_authorize:
    path: /api/auth
    controller: fos_oauth_server.controller.authorize:authorizeAction

# User
api_me:
    path: '/api/me'
    methods: ['GET']
    defaults:
        _controller: App\Controller\UserController::meAction
        _api_resource_class: App\Entity\User
        _api_collection_operation_name: 'me'

api_me_put:
    path: '/api/me'
    methods: ['PUT']
    defaults:
        _controller: App\Controller\UserController::meAction
        _api_resource_class: App\Entity\User
        _api_collection_operation_name: 'me_put'

api_register:
    path: '/api/register'
    methods: ['POST']
    defaults:
        _controller: App\Controller\UserController::registerAction
        _api_resource_class: App\Entity\User
        _api_collection_operation_name: 'register'

api_user_tree:
    path: '/api/me/tree'
    methods: ['GET']
    defaults:
        _controller: App\Controller\UserController::getUserTreeAction
        _api_resource_class: App\Entity\User
        _api_collection_operation_name: 'tree'

#emailMessage

api_message_inbox:
    path: '/api/email-messages-inbox'
    methods: ['GET']
    defaults:
        _controller: App\Controller\EmailMessageController::getUserMessagesAction
        _api_resource_class: App\Entity\EmailMessage
        _api_collection_operation_name: 'inbox'
